name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # TODO: we need to add compose ui tests
  # Android:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Job set up
  #       uses: ./.github/actions/job-set-up

  #     - run: ./gradlew clean testDebug -p androidApp/

  # TODO: all the tests that uses room are failing
  # TODO: NewsViewUnitTests is also failing maybe we should start with debuging this test
  iOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # this is only needed when running from separate branch
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: lennarthakkerkompas/test-github-actions
          token: ${{ secrets.TEST_GITHUB_ACTIONS_PATH }}
          path: private-repo

      - name: Job set up
        uses: ./.github/actions/job-set-up

      # use this when running from own preo
      # - name: iOS set up
      #   uses: ./.github/actions/ios-set-up

      # this is only needed when running from separate repo
      - name: iOS set up
        uses: ./.github/actions/ios-set-up
        with:
          private_repo_token: ${{ secrets.TEST_GITHUB_ACTIONS_PATH }}

      # this is only needed when running from separate repo
      - name: Build and Test iOS App
        working-directory: private-repo
        run: xcodebuild build test -project iosApp/iosApp.xcodeproj -scheme iosApp -configuration Debug -sdk iphoneos -destination "platform=iOS Simulator,name=iPhone 16,OS=18.6" -verbose
      # use this when running from own preo
      # - run: xcodebuild build test -project iosApp/iosApp.xcodeproj -scheme iosApp -configuration Debug -sdk iphoneos -destination "platform=iOS Simulator,name=iPhone 16,OS=18.6" -verbose

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: "/Users/runner/Library/Developer/Xcode/DerivedData/*"

  # KMP-Android:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Job set up
  #       uses: ./.github/actions/job-set-up

  #     - run: ./gradlew clean testDebugUnitTest -p shared/

  # KMP-iOS:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Job set up
  #       uses: ./.github/actions/job-set-up

  #     - run: if [[ $(uname -m) == 'arm64' ]]; then ./gradlew clean iosSimulatorArm64Test -p shared/; else ./gradlew clean iosX64Test -p shared/; fi
